# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ github.repository }}/backend
    DOCKERFILE: backend.Dockerfile
    CAPROVER_APP: concise
    DOCKER_REGISTRY: ghcr.io

on:
  push:
    tags:
      - 'bv[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
        export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
        echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build and test
      run: |
        cd ./backend
        go mod tidy
        go build -v ./...
        go test -v ./...

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Release to DockerHub
      shell: bash
      run: ./build_and_push.sh
      
    - name: Deploy App to CapRover
      uses: caprover/deploy-from-github@v1.0.1
      with:
        server: '${{ secrets.CAPROVER_SERVER }}'
        app: '${{ secrets.APP_NAME }}'
        token: '${{ secrets.APP_TOKEN }}'
        image: '${{ env.FULL_IMAGE_NAME }}'

