# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'bv[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: 
        - cd ./backend
        - go build -v ./...

    - name: Test
      run:
        - cd ./backend
        - go test -v ./...
    - uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: "./"
        files: |
          ./backend
          ./backend/captain-definition
          ./backend/Dockerfile
        outPath: deploy.tar
      
    - name: Deploy App to CapRover
      uses: caprover/deploy-from-github@v1.0.1
      with:
        server: '${{ secrets.CAPROVER_SERVER }}'
        app: '${{ secrets.APP_NAME }}'
        token: '${{ secrets.APP_TOKEN }}'

