# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
    CONTEXT_DIR: './'
    DOCKER_REGISTRY: ghcr.io
    BE_IMAGE_NAME: ${{ github.repository }}/backend
    BE_DOCKERFILE: backend.Dockerfile
    WEB_IMAGE_NAME: ${{ github.repository }}/web
    WEB_DOCKERFILE: web.Dockerfile

on:
  push:
    tags:
      - 'bv[0-9]+.[0-9]+.[0-9]+'
      - 'wv[0-9]+.[0-9]+.[0-9]+'

jobs:
  be-build-and-publish:
    if: startsWith(github.event.ref, 'refs/tags/bv')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$BE_IMAGE_NAME" >> $GITHUB_ENV
        export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$BE_IMAGE_NAME
        echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build and test
      run: |
        cd ./backend
        go mod tidy
        go build -v ./...
        go test -v ./...

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Release to Docker Registry
      shell: bash
      run: ./build_and_push.sh ${{ env.BE_DOCKERFILE }}
      
    - name: Deploy App to CapRover
      uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
      with:
        server: '${{ secrets.BE_CAPROVER_SERVER }}'
        app: '${{ secrets.BE_APP_NAME }}'
        token: '${{ secrets.BE_APP_TOKEN }}'
        image: '${{ env.FULL_IMAGE_NAME }}'

  web-build-and-publish:
    if: startsWith(github.event.ref, 'refs/tags/wv')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$WEB_IMAGE_NAME" >> $GITHUB_ENV
        export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$WEB_IMAGE_NAME
        echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Release to Docker Registry
      shell: bash
      run: ./build_and_push.sh ${{ env.WEB_DOCKERFILE }}
      
    - name: Deploy App to CapRover
      uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
      with:
        server: '${{ secrets.WEB_CAPROVER_SERVER }}'
        app: '${{ secrets.WEB_APP_NAME }}'
        token: '${{ secrets.WEB_APP_TOKEN }}'
        image: '${{ env.FULL_IMAGE_NAME }}'